---
- hosts: all
  become: true

  vars:
    server_name: archioweb.ch
  vars_files:
    - vars/secrets.vault

  roles:
    - role: ufw
      vars:
        ufw_allow:
          - proto: tcp
            port: '{{ server_ssh_port }}'
          - proto: tcp
            port: 80
          - proto: tcp
            port: 443
    - role: archioweb

  tasks:
    - name: Set hostname
      hostname:
        name: '{{ server_name }}'

    - name: Set up motd
      copy:
        src: motd
        dest: /etc/update-motd.d/99-banner
        owner: root
        group: root
        mode: 0755
      tags: [motd]
