---
- hosts: all
  become: true

  vars:
    server_name: archioweb.ch

  roles:
    - role: docker

  tasks:
    - name: Set hostname
      hostname:
        name: '{{ server_name }}'

    - name: Set up motd
      copy:
        src: motd
        dest: /etc/update-motd.d/99-banner
        owner: root
        group: root
        mode: 0755
      tags: [motd]

    - name: Create Docker Compose directory
      file:
        path: /srv/archioweb
        owner: root
        group: root
        mode: 0750
        state: directory
      tags: [archioweb]

    - name: Copy Docker Compose configuration
      copy:
        src: compose.yml
        dest: /srv/archioweb/compose.yml
        owner: root
        group: root
      tags: [archioweb]
