---
- hosts: all
  become: true

  vars:
    server_name: archioweb.ch

  roles:
    - role: docker

  tasks:
    - name: Set hostname
      hostname:
        name: '{{ server_name }}'

    - name: Set up motd
      copy:
        src: motd
        dest: /etc/update-motd.d/99-banner
        owner: root
        group: root
        mode: 0755
      tags: [motd]
