name: archioweb

services:
  rp:
    image: 'traefik:v3.5.2'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rp-dashboard.entrypoints=public-https'
      - 'traefik.http.routers.rp-dashboard.rule=Host(`rp.archioweb.ch`)'
      - 'traefik.http.routers.rp-dashboard.middlewares=rp-dashboard-auth'
      - 'traefik.http.routers.rp-dashboard.service=api@internal'
      - 'traefik.http.routers.rp-dashboard.tls=true'
      - 'traefik.http.routers.rp-dashboard.tls.certresolver=letsencrypt'
      - 'traefik.http.middlewares.rp-dashboard-auth.basicauth.usersFile=/etc/traefik/htpasswd'
      - 'traefik.http.middlewares.rp-dashboard-auth.basicauth.realm=Protected'
      # Dummy service for Swarm port detection. The port can be any valid
      # integer value.
      - 'traefik.http.services.rp-dashboard.loadbalancer.server.port=9999'
    networks:
      - demo-web
      - express-exercise-web
      - qimg-web
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - 'rp-data:/var/lib/traefik:rw'
      - '/srv/archioweb/rp/htpasswd:/etc/traefik/htpasswd:ro'
      - '/srv/archioweb/rp/traefik.yml:/etc/traefik/traefik.yml:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  demo-app:
    image: 'ghcr.io/mediacomem/comem-rest-demo:3.0.0'
    depends_on:
      - demo-db
    environment:
      - AUTH_TOKEN
      - BASE_URL=https://demo.archioweb.ch
      - DATABASE_URL=mongodb://demo-db:27017/demo
      - DEBUG=demo:*
    init: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=archioweb_demo-web'

      - 'traefik.http.routers.archioweb-demo-insecure.entrypoints=public-http'
      - 'traefik.http.routers.archioweb-demo-insecure.rule=Host(`demo.archioweb.ch`)'
      - 'traefik.http.routers.archioweb-demo-insecure.middlewares=archioweb-demo-insecure-redirect'
      - 'traefik.http.middlewares.archioweb-demo-insecure-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.archioweb-demo-insecure-redirect.redirectscheme.permanent=true'

      - 'traefik.http.routers.archioweb-demo.entrypoints=public-https'
      - 'traefik.http.routers.archioweb-demo.rule=Host(`demo.archioweb.ch`)'
      - 'traefik.http.routers.archioweb-demo.tls=true'
      - 'traefik.http.routers.archioweb-demo.tls.certresolver=letsencrypt'
    networks:
      - demo-db
      - demo-web
    restart: unless-stopped

  demo-db:
    image: mongo:8.0.13
    networks:
      - demo-db
    restart: unless-stopped
    volumes:
      - demo-db-data:/data/db

  express-exercise:
    image: 'ghcr.io/mediacomem/comem-archioweb-express-exercise:1.0.2'
    environment:
      - DEBUG=archioweb:express:*
    init: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=archioweb_express-exercise-web'

      - 'traefik.http.routers.archioweb-express-exercise-insecure.entrypoints=public-http'
      - 'traefik.http.routers.archioweb-express-exercise-insecure.rule=Host(`express.archioweb.ch`)'
      - 'traefik.http.routers.archioweb-express-exercise-insecure.middlewares=archioweb-express-exercise-insecure-redirect'
      - 'traefik.http.middlewares.archioweb-express-exercise-insecure-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.archioweb-express-exercise-insecure-redirect.redirectscheme.permanent=true'

      - 'traefik.http.routers.archioweb-express-exercise.entrypoints=public-https'
      - 'traefik.http.routers.archioweb-express-exercise.rule=Host(`express.archioweb.ch`)'
      - 'traefik.http.routers.archioweb-express-exercise.tls=true'
      - 'traefik.http.routers.archioweb-express-exercise.tls.certresolver=letsencrypt'
    networks:
      - express-exercise-web
    restart: unless-stopped

  qimg-app:
    image: 'ghcr.io/mediacomem/comem-qimg:2.1.0'
    depends_on:
      - qimg-db
    environment:
      DEBUG: qimg:*
      QIMG_ADMIN_TOKEN:
      QIMG_BASE_URL: https://qimg.archioweb.ch
      QIMG_DATABASE_URL: postgresql://qimg:${QIMG_DATABASE_PASSWORD}@qimg-db/qimg
      QIMG_IMAGE_MAX_SIZE: 5242880
      QIMG_IMAGE_QUOTA: 50
    init: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=archioweb_qimg-web'

      - 'traefik.http.routers.archioweb-qimg-insecure.entrypoints=public-http'
      - 'traefik.http.routers.archioweb-qimg-insecure.rule=Host(`qimg.archioweb.ch`)'
      - 'traefik.http.routers.archioweb-qimg-insecure.middlewares=archioweb-qimg-insecure-redirect'
      - 'traefik.http.middlewares.archioweb-qimg-insecure-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.archioweb-qimg-insecure-redirect.redirectscheme.permanent=true'

      - 'traefik.http.routers.archioweb-qimg.entrypoints=public-https'
      - 'traefik.http.routers.archioweb-qimg.rule=Host(`qimg.archioweb.ch`)'
      - 'traefik.http.routers.archioweb-qimg.tls=true'
      - 'traefik.http.routers.archioweb-qimg.tls.certresolver=letsencrypt'
    networks:
      - qimg-db
      - qimg-web
    restart: unless-stopped

  qimg-db:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_PASSWORD: ${QIMG_DATABASE_PASSWORD}
      POSTGRES_USER: qimg
      POSTGRES_DB: qimg
    networks:
      - qimg-db
    restart: unless-stopped
    volumes:
      - qimg-db-data:/var/lib/postgresql/data

networks:
  demo-db:
  demo-web:
  express-exercise-web:
  qimg-db:
  qimg-web:

volumes:
  demo-db-data:
  qimg-db-data:
  rp-data:
