---
- name: Install UFW
  apt:
    name: ufw
    state: present
  tags: [ufw]

- name: Configure UFW TCP ports
  ufw:
    rule: allow
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
    state: enabled
  with_items: '{{ ufw_allow }}'
  tags: [ufw]

- name: Enable UFW
  ufw:
    state: enabled
  tags: [ufw]
