---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
  tags: [ufw]

- name: Configure UFW TCP ports
  community.general.ufw:
    rule: allow
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  loop: '{{ ufw_allow }}'
  tags: [ufw]

- name: Deny all other incoming traffic by default
  community.general.ufw:
    default: deny
    direction: incoming
  tags: [ufw]

- name: Enable UFW
  community.general.ufw:
    state: enabled
  tags: [ufw]
