name: archioweb

services:
  rp:
    image: 'traefik:v3.1'
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.web.address=:80'
    networks:
      - demo-web
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - 'rp-data:/var/lib/traefik:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  demo-app:
    image: 'ghcr.io/mediacomem/comem-rest-demo:2.0.1'
    depends_on:
      - demo-db
    environment:
      - BASE_URL=http://archioweb.local
      - DATABASE_URL=mongodb://demo-db:27017/demo
      - DEBUG=demo:*
    init: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=archioweb_demo-web'
      - 'traefik.http.routers.archioweb-demo.rule=Host(`archioweb.local`)'
      - 'traefik.http.routers.archioweb-demo.entrypoints=web'
    networks:
      - demo-db
      - demo-web
    ports:
      - '3000:3000'

  demo-db:
    image: mongo:7.0.14
    networks:
      - demo-db
    volumes:
      - demo-db-data:/data/db

networks:
  demo-db:
  demo-web:

volumes:
  demo-db-data:
  rp-data:
