#!/usr/bin/env bash

printf "    _          _    _  _____      __   _"
printf "\n"
printf "   /_\\  _ _ __| |_ (_)/ _ \\ \\    / /__| |__"
printf "\n"
printf "  / _ \\| '_/ _| ' \\| | (_) \\ \\/\\/ / -_) '_ \\"
printf "\n"
printf " /_/ \\_\\_| \\__|_||_|_|\\___/ \\_/\\_/\\___|_.__/"
printf "\n\n"
